<?php

/**
 * @file
 * Install, uninstall and update functions for Patreon Extras.
 */

/**
 * Implements hook_install().
 */
function patreon_extras_install() {
  patreon_extras_update_pledge_data();
}

/**
 * Implements hook_uninstall().
 */
function patreon_extras_uninstall() {
  // Delete set variables.
  db_delete('variable')
    ->condition('name', 'patreon_extras_%', 'LIKE')
    ->execute();
}
