version: '3'
services:
    application:
        environment:
          XDEBUG_CONFIG: 'remote_host=host.docker.internal'
          PHP_IDE_CONFIG: 'serverName=vscode'
          IDE_KEY: 'VSCODE'
          DATABASE_PASSWORD: 'wakizashi'
          DATABASE_USER: 'root'
          DATABASE_HOST: 'host.docker.internal'
          DATABASE_DATABASE: 'dmge'
          DATABASE_PREFIX: ''
        container_name: 'dmge'
        image: 'dev:xdebug'
        ports:
          - '9090:8080'
        volumes:
          - '/archive/www/dmge:/var/www/html'
          - '/archive/www/dmge/sites:/var/www/html/sites'
          - '/archive/www/dmge/sites/all:/var/www/html/sites/all'
          - '/archive/www/dmge/sites/default:/var/www/html/sites/default'
        extra_hosts:
          - 'host.docker.internal:host-gateway'