<?php
/**
 * @file
 * Code for the Content feature.
 */

include_once 'mc.features.inc';

/**
 * Implements hook_preprocess_block();
 */
function mc_preprocess_block(&$vars) {
  $block = $vars['block'];

  if (function_exists('fe_block_get_machine_name')) {
    $machine_name = fe_block_get_machine_name($block->delta);
  }
  if (empty($machine_name)) {
    $machine_name = drupal_html_class($block->delta);
  }

  if(!empty($machine_name)) {
    $vars['classes_array'][] = 'block-' . str_replace('_', '-', $machine_name);
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function mc_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'mc');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Invokes hook_preprocess_page().
 */
function mc_preprocess_page(&$variables) {
  $path = drupal_get_path('module', 'mc');
  drupal_add_css($path . '/css/mc.css');
  drupal_add_js($path . '/js/jquery.matchHeight-min.js');
  drupal_add_js($path . '/js/mc.init.js', array('scope' => 'footer'));
}

/**
 * Helper function converts hex to rgb.
 */
function HEX_to_RGB($hex, $alpha = false) {
  $hex = str_replace('#', '', $hex);
  $length = strlen($hex);

  $rgb['r'] = hexdec($length == 6 ? substr($hex, 0, 2) : ($length == 3 ? str_repeat(substr($hex, 0, 1), 2) : 0));
  $rgb['g'] = hexdec($length == 6 ? substr($hex, 2, 2) : ($length == 3 ? str_repeat(substr($hex, 1, 1), 2) : 0));
  $rgb['b'] = hexdec($length == 6 ? substr($hex, 4, 2) : ($length == 3 ? str_repeat(substr($hex, 2, 1), 2) : 0));

  if ($alpha) {
    $rgb['a'] = $alpha;
  }
  return implode(array_keys($rgb)) . '(' . implode(', ', $rgb) . ')';
}

function mc_form_alter(&$form, &$form_state) {
  $path = drupal_get_path('module', 'mc');
  if ($form['form_id'] === 'user_register_form ') {
    $form['#attached']['js'] = array(
       $path . '/mc.register.js',
    );
  }
}
