<?php
/**
 * @file
 * Code for the DMGE - Artists feature.
 */

include_once 'dmge_artists.features.inc';

/**
 * If the artist has a link in their profile, it might be a YouTube link.
 * If it IS a YouTube link, then lets go to their channel and download all
 * their videos as unpublished videos on the site.
 * TODO: Build the user a VBO view for publishing videos.
 */

/**
 * Doing this on cron?
 */
function dmge_artists_cron() {
  //
}

/**
 * Hard Coded to Manny.
 */
function dmge_artists_retrieve_uploads($channelId = 'UCrsCjHT8tJ1vpSkvLoYji3g', $author_node_id = 5) {
  $apiKey = variable_get('youtube_apikey', 'AIzaSyAE_8NGF6cwkpDZ4nKrogAIASzxpdT-gcw');
  $baseUrl = 'https://www.googleapis.com/youtube/v3/';

  $params = [
    'id'=> $channelId,
    'part'=> 'contentDetails',
    'key'=> $apiKey,
  ];
  $url = $baseUrl . 'channels?' . http_build_query($params);
  $json = drupal_http_request($url);
  $json = json_decode($json->data, true);

  $playlist = $json['items'][0]['contentDetails']['relatedPlaylists']['uploads'];

  $params = [
    'part'=> 'snippet',
    'playlistId' => $playlist,
    'maxResults'=> '50',
    'key'=> $apiKey,
  ];
  $url = $baseUrl . 'playlistItems?' . http_build_query($params);
  $json = drupal_http_request($url);
  $json = json_decode($json->data, true);

  $videos = [];
  foreach($json['items'] as $video) {
    $vid = $video['snippet']['resourceId']['videoId'];
    $videos[$vid] = array(
      'title' => $video['snippet']['title'],
      'videoid' => $vid,
      'thumbnail' => $video['snippet']['thumbnails']['high']['url'],
    );
  }

  while(isset($json['nextPageToken'])) {
    $nextUrl = $url . '&pageToken=' . $json['nextPageToken'];
    $json = drupal_http_request($nextUrl);
    $json = json_decode($json->data, true);
    foreach($json['items'] as $video) {
      $vid = $video['snippet']['resourceId']['videoId'];
      $videos[$vid] = array(
        'title' => $video['snippet']['title'],
        'videoid' => $vid,
        'thumbnail' => $video['snippet']['thumbnails']['high']['url'],
      );
    }
  }
  if (empty($videos)) {
    return FALSE;
  }
  print 'Retrieved ' . count($videos) . ' videos';
  print "\n";
  return $videos;
}


/**
 * Import videos as nodes.
 */
function dmge_artists_import_videos($author_node_id = 5) {
  if ($videos = dmge_artists_retrieve_uploads()) {
    foreach ($videos as $vid => $video) {
      print 'Starting ' . $vid;
      print "\n\n";
      print_r($video);
      print "\n\n";
      $node = new stdClass();
      $node->title = $video['title'];
      $node->type = 'resource';
      node_object_prepare($node);
      print 'Prepared node.';
      print "\n";
      $node->language = LANGUAGE_NONE;
      $node->uid = 1;
      $node->status = 1;
      $node->promote = 0;
      $node->comment = 0;
      print 'Retrieving taxonomies.';
      print "\n";
      $taxonomy = taxonomy_vocabulary_machine_name_load('resource_link');
      $tid = taxonomy_get_term_by_name('YouTube');
      print 'Assigned taxonomies.';
      print "\n";
      print 'Getting thumbnail.';
      print "\n\n";
      $file = system_retrieve_file($video['thumbnail'], NULL, TRUE);
      $file->status = 1;
      $node->field_image[LANGUAGE_NONE][0] = (array) $file;
      print 'Assigned thumbnail.';
      print "\n";
      print 'Assigning resource links.';
      print "\n\n";
      $node->field_map_author[LANGUAGE_NONE][0]['target_id'] = $author_node_id;
      $node->field_resource_links[LANGUAGE_NONE][0]['field_resource_link_type'][LANGUAGE_NONE][0]['tid'] = $tid;
      $node->field_resource_links[LANGUAGE_NONE][0]['field_resource_link'][LANGUAGE_NONE][0]['#default_value']['url'] = 'https://www.youtube.com/watch?v=' . $vid;
      print "\n\n";
      print_r($node);
      print "\n\n";
      print 'Done.  Saving node.';
      print "\n";
      node_save($node);
      print 'Saved ' . $node->nid . ' for vid ' . $vid;
      print "\n";
      break;
    }
  }
}
