<?php
/**
 * @file
 * Code for the DMGE - Artists feature.
 */

include_once 'dmge_artists.features.inc';

/**
 * If the artist has a link in their profile, it might be a YouTube link.
 * If it IS a YouTube link, then lets go to their channel and download all
 * their videos as unpublished videos on the site.
 * TODO: Build the user a VBO view for publishing videos.
 */

/**
 * Doing this on cron.
 */
function dmge_artists_cron() {
  //
}

function dmge_artists_retrieve_uploads($channel_id = 'UCrsCjHT8tJ1vpSkvLoYji3g') {
  ini_set("allow_url_fopen", 1);
  $youtube_apikey = variable_get('youtube_apikey', 'AIzaSyAE_8NGF6cwkpDZ4nKrogAIASzxpdT-gcw');
  $url = 'https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=' . $channel_id . '&key=' . $youtube_apikey;
  $json = file_get_contents($url);
  $obj = json_decode($json);
  print($obj);
}
